name: Run unit tests

on: [pull_request]

jobs:
    phpunit:
        name: Run Phpunit
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php:
                    - 7.4
                    - 8.0
                    - 8.1
                dependencies:
                    - lowest
                    - highest
                include:
                    -   php-version: 8.2
                        composer-options: --ignore-platform-reqs
        steps:
            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  tools: composer:2
                  coverage: none

            - uses: actions/checkout@v2

            - uses: ./.github/actions/composer-install

            - run: ./vendor/bin/phpunit

    infection:
        name: Run Infection
        runs-on: ubuntu-latest
        steps:
            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: latest
                  coverage: pcov

            - uses: actions/checkout@v2

            - uses: ./.github/actions/composer-install

            - run: ./vendor/bin/infection --min-msi=56 --min-covered-msi=85 --threads=4 --logger-github

    coverage:
        name: Code Coverage
        runs-on: ubuntu-latest
        steps:
            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                php-version: latest
                coverage: pcov

            - uses: actions/checkout@v1

            - uses: ./.github/actions/composer-install

            - run: ./vendor/bin/phpunit --coverage-clover=build/logs/clover.xml

            - name: Coveralls
              env:
                  COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                composer global require php-coveralls/php-coveralls
                php-coveralls --coverage_clover=build/logs/clover.xml -v
